### ISSUE TITLE
no issue just a question

### ISSUE THREAD

**Issue by alexthepink95** [TBulbaDB/PoGoMITM#2]
i was actually working on the same fork on converting it to 0.35 i converted the pogoprotos but never finished adding all the parsing info for it...
Q i wanted to know first off if this was using 0.35 protos?
if not im gonna add them...

**Comment by TBulbaDB** [comment]
I've just updated the Protos to the latest, but feel free to contribute on other stuff as you like, thanks.

**Comment by alexthepink95** [comment]
ok cool thanx for letting me know it might be easier for some users to just type their ip instead of editing any files using the console read method 
 i am gonna be using this to compare the difference between the my phone and my teams bot
