### ISSUE TITLE
an issue and a question

### ISSUE THREAD

**Issue by alexthepink95** [TBulbaDB/PoGoMITM#3]
is there anyway i can make the web server remotely viewable?
isnt it supposed to dumps a log of the decoded requests and the raw requests?

**Comment by TBulbaDB** [comment]
Hi, 

You can see the web server from anywhere, if it's running on your home, just enable port forwarding on your router and make sure windows firewall lets you get through. 

It does dump the logs, just edit the pogomitm.exe.config and set DumpRaw and DumpProcessed to true. Also make sure you have <add key="DataDumpers" value="FileDumper" />

**Comment by TBulbaDB** [comment]
Next release will fix the dump problems.
