### ISSUE TITLE
[FEATURE] Add option to dump raw signature

### ISSUE THREAD

**Issue by Grover-c13** [TBulbaDB/PoGoMITM#4]
Would like an option to dump raw sigs (decrypted) if possible, can be handy for checking stuff that proto implementations might mess up (checking if something is repeated not currently marked etc).

**Comment by TBulbaDB** [comment]
Will add, thanks for the suggestion. Also working on the history feature we've talked about.

**Comment by TBulbaDB** [comment]
Coded, coming up with the next release

**Comment by TBulbaDB** [comment]
New release have this.
