### ISSUE TITLE
Occasionaly signature not decrypted

### ISSUE THREAD

**Issue by Grover-c13** [TBulbaDB/PoGoMITM#6]
Sometimes the signature is not decrypted, very uncommon bug. About 1/10 requests

**Comment by TBulbaDB** [comment]
I'm using the js, possibly there might be some problems sometimes, will look into that, thanks for reporting.

**Comment by thekjohn** [comment]
Where should I see the decyrpted signature ?
I can see only EncryptedSignature :(

**Comment by TBulbaDB** [comment]
@thekjohn Next release will do that

**Comment by thekjohn** [comment]
ok, thanks! you rock!

**Comment by TBulbaDB** [comment]
@Grover-c13 Couldn't reproduce I'm afraid.
