### ISSUE TITLE
No PlayerUpdate support?

### ISSUE THREAD

**Issue by thekjohn** [TBulbaDB/PoGoMITM#7]
Maybe I am wrong, or just messing something up, but I can't see any PlayerUpdate requests in the logs.
Because I am on wifi, I can't go too far from the router, but I went away ~30 meters, which should definitely trigger PlayerUpdate.

Is there any chance the client no longer use PlayerUpdate, and the servers rely only the coordinates in request envelopes and location fixes?

**Comment by TBulbaDB** [comment]
I've checked outside, it does log PlayerUpdates when you start moving.

**Comment by thekjohn** [comment]
very strange :o how often? I mean in meters

**Comment by thekjohn** [comment]
btw is there any way on android to set up the proxy though mobile data?

**Comment by TBulbaDB** [comment]
Actually, I didn't get any GetPlayer requests, I'll look into it.

I'm routing my requests through another phone and set it on the wifi, some mentioned proxy settings in mobile networks/apn but I couldn't get it work.

**Comment by thekjohn** [comment]
GetPlayer is okay for me. strange...

**Comment by thekjohn** [comment]
I switched to 2.4 Ghz Wifi, went away ~80 meters and still no PlayerUpdate request logged :(

**Comment by thekjohn** [comment]
hehe, mobile proxy is working for me, so I go for a walk :)

**Comment by thekjohn** [comment]
15 minutes of walk, still no PlayerUpdate request

**Comment by thekjohn** [comment]
status update: I did another walk, after updated to your latest (huge) commit, but still no PlayerUpdate.

**Comment by TBulbaDB** [comment]
Maybe they just don't use it anymore.

**Comment by thekjohn** [comment]
You were able to log any?

**Comment by TBulbaDB** [comment]
Nope. but I've checked the code, it should log it if there was any, not sure what's going on

**Comment by TBulbaDB** [comment]
I think this is somehow resolved, right? :)

**Comment by thekjohn** [comment]
if resolved means it is confirmed that there are no such a requests, then yes :)
